// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency_keys.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
    id, user_id, response_code, response_body
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, response_code, response_body, created_at
`

type CreateIdempotencyKeyParams struct {
	ID           string    `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	ResponseCode int32     `json:"response_code"`
	ResponseBody []byte    `json:"response_body"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, createIdempotencyKey,
		arg.ID,
		arg.UserID,
		arg.ResponseCode,
		arg.ResponseBody,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, user_id, response_code, response_body, created_at FROM idempotency_keys
WHERE id = $1 AND user_id = $2
`

type GetIdempotencyKeyParams struct {
	ID     string    `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyKey, arg.ID, arg.UserID)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}
